const fs = require('fs');

const people = [
  "Albert Einstein, Física Teórica",
  "Marie Curie, Radioatividade",
  "Isaac Newton, Física e Matemática",
  "Charles Darwin, Biologia Evolutiva",
  "Nikola Tesla, Engenharia Elétrica",
  "Galileo Galilei, Astronomia e Física",
  "Ada Lovelace, Computação",
  "Stephen Hawking, Cosmologia",
  "Alan Turing, Ciência da Computação",
  "Richard Feynman, Eletrodinâmica Quântica",
  "Niels Bohr, Estrutura Atômica",
  "Rosalind Franklin, Cristalografia de DNA",
  "Max Planck, Mecânica Quântica",
  "Johannes Kepler, Astronomia",
  "Carl Sagan, Astronomia e Divulgação",
  "Leonardo da Vinci, Polímata",
  "Louis Pasteur, Microbiologia",
  "Michael Faraday, Eletromagnetismo",
  "James Clerk Maxwell, Eletromagnetismo",
  "Erwin Schrödinger, Mecânica Quântica",
  "Enrico Fermi, Física Nuclear",
  "Paul Dirac, Mecânica Quântica",
  "Werner Heisenberg, Princípio da Incerteza",
  "Edwin Hubble, Cosmologia",
  "Lise Meitner, Fissão Nuclear",
  "Alexander Fleming, Penicilina",
  "Gregor Mendel, Genética",
  "Dmitri Mendeleev, Tabela Periódica",
  "Antoine Lavoisier, Química Moderna",
  "John von Neumann, Computação e Matemática",
  "Srinivasa Ramanujan, Teoria dos Números",
  "Kurt Gödel, Lógica Matemática",
  "Évariste Galois, Teoria de Grupos",
  "Carl Friedrich Gauss, Matemática",
  "Leonhard Euler, Matemática",
  "Euclides, Geometria",
  "Arquimedes, Matemática e Física",
  "Pitágoras, Matemática",
  "Hipácia de Alexandria, Matemática e Astronomia",
  "Grace Hopper, Computação",
  "Katherine Johnson, Matemática Orbital",
  "Margaret Hamilton, Engenharia de Software",
  "Tim Berners-Lee, World Wide Web",
  "Claude Shannon, Teoria da Informação",
  "Linus Pauling, Química Quântica",
  "Barbara McClintock, Genética",
  "Jonas Salk, Vacina da Pólio",
  "Jane Goodall, Primatologia",
  "Rachel Carson, Biologia Marinha",
  "Alexander von Humboldt, Geografia e Naturalismo",
  "Emmy Noether, Álgebra Abstrata",
  "Sofya Kovalevskaya, Matemática",
  "Chien-Shiung Wu, Física Experimental",
  "Jocelyn Bell Burnell, Astrofísica",
  "Vera Rubin, Matéria Escura",
  "Subrahmanyan Chandrasekhar, Astrofísica",
  "Satyendra Nath Bose, Física Quântica",
  "Abdus Salam, Física Teórica",
  "C.V. Raman, Espalhamento de Luz",
  "Hideki Yukawa, Física Nuclear",
  "Shin'ichiro Tomonaga, Eletrodinâmica Quântica",
  "Chen-Ning Yang, Física de Partículas",
  "Tsung-Dao Lee, Física de Partículas",
  "Steven Weinberg, Força Eletrofraca",
  "Sheldon Glashow, Força Eletrofraca",
  "Murray Gell-Mann, Quarks",
  "Peter Higgs, Bóson de Higgs",
  "Kip Thorne, Ondas Gravitacionais",
  "Roger Penrose, Buracos Negros",
  "Arthur Eddington, Astrofísica",
  "Georges Lemaître, Big Bang",
  "John Wheeler, Buracos Negros",
  "Hugh Everett, Muitos Mundos",
  "David Bohm, Física Quântica",
  "John Bell, Teorema de Bell",
  "Alain Aspect, Emaranhamento Quântico",
  "Anton Zeilinger, Informação Quântica",
  "John Clauser, Mecânica Quântica",
  "Giorgio Parisi, Sistemas Complexos",
  "Syukuro Manabe, Climatologia",
  "Klaus Hasselmann, Climatologia",
  "Andrea Ghez, Buraco Negro Supermassivo",
  "Reinhard Genzel, Buraco Negro Supermassivo",
  "Michel Mayor, Exoplanetas",
  "Didier Queloz, Exoplanetas",
  "James Peebles, Cosmologia Física",
  "Arthur Ashkin, Pinças Ópticas",
  "Gérard Mourou, Lasers",
  "Donna Strickland, Lasers",
  "Rainer Weiss, LIGO",
  "Barry Barish, LIGO",
  "David Thouless, Transições de Fase Topológicas",
  "F. Duncan M. Haldane, Fases Topológicas",
  "J. Michael Kosterlitz, Transições Topológicas",
  "Takaaki Kajita, Oscilação de Neutrinos",
  "Arthur B. McDonald, Oscilação de Neutrinos",
  "Isamu Akasaki, LED Azul",
  "Hiroshi Amano, LED Azul",
  "Shuji Nakamura, LED Azul",
  "François Englert, Mecanismo de Brout-Englert-Higgs",
  "Serge Haroche, Óptica Quântica",
  "David J. Wineland, Óptica Quântica",
  "Saul Perlmutter, Expansão Acelerada do Universo",
  "Brian P. Schmidt, Expansão Acelerada do Universo",
  "Adam G. Riess, Expansão Acelerada do Universo",
  "Andre Geim, Grafeno",
  "Konstantin Novoselov, Grafeno",
  "Charles K. Kao, Fibras Ópticas",
  "Willard S. Boyle, Sensor CCD",
  "George E. Smith, Sensor CCD",
  "Yoichiro Nambu, Quebra Espontânea de Simetria",
  "Makoto Kobayashi, Quebra Espontânea de Simetria",
  "Toshihide Maskawa, Quebra Espontânea de Simetria"
];

let arr = [];
let i = 1;
for (const p of people) {
  const [name, area] = p.split(', ');
  arr.push({
    id: `bio-${i}`,
    title: `Biografia: ${name}`,
    titlePt: `Biografia: ${name}`,
    source: 'Arquivo Histórico de Biografias',
    sourceCategory: 'biography',
    link: 'https://pt.wikipedia.org/wiki/' + name.replace(/ /g, '_'),
    pubDate: new Date().toLocaleDateString('pt-BR'),
    summary: `${name} is one of the most prominent scientists in history, widely known for their profound contributions to ${area}. Their work reshaped our understanding of the universe.`,
    summaryPt: `${name} é um(a) dos(as) cientistas mais proeminentes da história, amplamente reconhecido(a) por suas contribuições profundas à área de ${area}. Seu trabalho reformulou nossa compreensão do universo.`,
    keyTakeaway: `Pioneirismo em ${area}.`,
    author: 'Equipe Editorial RACT',
    readTime: '4 min',
    tags: ['Biografia', area],
  });
  i++;
}

fs.writeFileSync('src/data/biographies.ts', `export const BIOGRAPHIES_DATA = ${JSON.stringify(arr, null, 2)};`);
